name: Bug Report
description: File a Bug/Issue
title: "[BUG] title"
labels: ["bug"]
body: 
  - type: textarea
    attributes: 
      label: Bug description
      description: Please describe the bug you're noticing
    validations: 
      required: false
  - type: textarea
    attributes: 
      label: Reproduction steps
      description: Please list out the steps to reproduce this issue
    validations: 
      required: false
      
  - type: input 
     attributes:
      label: Effected URL
      placeholder: Please input the effected URL we can see the issue
     validations: 
      required: false
  - type: textarea 
    attributes: 
      label: Anything else? 
      description: Links? Screenshots and/or screenrecordings? Anything that will provide us with more context about the issue you're encountering. 
      placeholder: Tip💡 You can attach images or log files by clicking this area to highlight it and then dragging files in! 
    validations: 
      required: false
