name: 🚨 Report a Critical Issue
description: File a Critical Issue
title: "[CRITICAL ISSUE] title"
labels: ["critical issue"]
body: 
  - type: textarea
    attributes: 
      label: Critical Issue description
      description: Please describe the bug you're noticing
    validations: 
      required: true
  - type: textarea
    attributes: 
      label: Reproduction steps
      description: Please list out the steps to reproduce this issue
    validations: 
      required: true
  - type: textarea 
    attributes: 
      label: When did you first notice this issue? 
      description: Please share when the issue was first discovered 
    validations: 
      required: false
