name: "Deliverable Issue"
description: "This will be created by the Form Factory team"
title: "[TASK] title"
labels: ["task"]
body: 
  - type: textarea
    attributes:
      label: "Description"
      description: "Please describe the new feature or task."
    validations: 
      required: true
  
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Confirm the must have elements of this feature"
    validations: 
      required: true
  
  - type: textarea
    attributes:
      label: "QA Strategy"
      description: "How do you plan to QA this task?"
    validations: 
      required: true
  
  - type: textarea
    attributes:
      label: "Tasks"
      description: "Please create a task list here."
    validations: 
      required: true
  
  - type: input
    attributes:
      label: "Form Factory Estimate"
      placeholder: "Provide the Form Factory estimate here."
    validations: 
      required: false
  
  - type: input
    attributes:
      label: "Latest Preview Link"
      placeholder: "Provide the latest preview link here."
    validations: 
      required: false
  
  - type: input
    attributes:
      label: "Delivery Date"
      placeholder: "Provide the delivery date here."
    validations: 
      required: true
