name: "📝 New Project Task"
description: "Details and criteria for a new project task or feature"
title: "[TASK] title"
labels: ["task"]
body: 
  - type: textarea
    attributes:
      label: "Feature Description"
      description: "Please describe the new feature or task."
    validations: 
      required: true
  
  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Please confirm that the task meets the following criteria."
      options: 
        - label: "Criterion 1"
        - label: "Criterion 2"
        - label: "Criterion 3"
    validations: 
      required: true
  
  - type: textarea
    attributes:
      label: "QA Strategy"
      description: "How do you plan to QA this task?"
    validations: 
      required: true
  
  - type: textarea
    attributes:
      label: "Tasks"
      description: "Please create a task list here."
    validations: 
      required: true
  
  - type: input
    attributes:
      label: "Form Factory Estimate"
      placeholder: "Provide the Form Factory estimate here."
    validations: 
      required: false
  
  - type: input
    attributes:
      label: "Latest Preview Link"
      placeholder: "Provide the latest preview link here."
    validations: 
      required: false
  
  - type: input
    attributes:
      label: "Delivery Date"
      placeholder: "Provide the delivery date here."
    validations: 
      required: true
