name: General Issue
description: File a general issue
title: "general issue"
body: 
  - type: textarea
    attributes: 
      label: Description 
      description: Please describe the issue 
    validations: 
      required: true
