name: New Feature
description: Request a new feature
title:  "[NEW FEATURE] title"
labels: ["new feature"]
body: 
  - type: textarea
    attributes:
     label: New Feature Description
     description: Please describe the new feature
    validations: 
     required: false
  - type: dropdown
    id: Timeline
    attributes:
      label: Timeline
      description: Please let us know the timeline for getting this feature live (Note❗️ we will need to ensure the feature can be done in the timeline provided based on specs)
      options:
        - End of current sprint
        - Next sprint 
        - Lets discuss
    validations:
      required: true
  - type: textarea 
    attributes: 
      label: Anything else? 
      description: Links? Screenshots and/or screenrecordings? Anything that will provide us with more context about the issue you're encountering. 
      placeholder: Tip💡 You can attach images or log files by clicking this area to highlight it and then dragging files in! 
    validations: 
      required: false
