name: Add new issues to project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
    - name: Add issue to project
      uses: actions/github-script@v5
      with:
        script: |
          // Get the id of the project titled "Internal-Tasks"
          const { data: projects } = await github.rest.projects.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const project = projects.find(p => p.name === "Internal-Tasks");

          // Get the id of the "To do" column
          const { data: columns } = await github.rest.projects.listColumns({
            project_id: project.id,
          });
          const column = columns.find(c => c.name === "To do");

          // Create a card for the issue in the "To do" column
          await github.rest.projects.createCard({
            column_id: column.id,
            content_id: context.issue.id,
            content_type: "Issue",
          });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
