name: Auto-assign acgsia-tff when "QA needed" label is added

on:
  issues:
    types: [labeled]

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "QA needed" label
        if: contains(github.event.issue.labels.*.name, 'QA needed')
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ["acgsia-tff"]
            })
