name: Add Issue to Internal-Tasks Project

on:
  issues:
    types: [opened]

jobs:
  addIssueToProject:
    runs-on: ubuntu-latest

    steps:
      - name: Add issue to project
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            const { data: projects } = await octokit.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const projectId = projects.find(project => project.name === 'Internal-Tasks').id;

            const { data: columns } = await octokit.projects.listColumns({
              project_id: projectId
            });

            const columnId = columns.find(column => column.name === 'To do').id;

            await octokit.projects.createCard({
              column_id: columnId,
              content_id: context.issue.id,
              content_type: 'Issue'
            });
