name: Auto Assign Author

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_assign_author:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set pull request author as assignee
        run: |
          echo "GITHUB_ACTOR=${GITHUB_ACTOR}" >> $GITHUB_ENV
          echo "::set-output name=author::${{ github.actor }}"
        id: assign_author

      - name: Update pull request
        uses: peter-evans/update-pull-request@v3
        with:
          author: ${{ steps.assign_author.outputs.author }}
          token: ${{ secrets.GITHUB_TOKEN }}
