name: Add "needs code review" label and replace with "QA Needed" label on approved pull request

on:
  pull_request:
    types: [opened, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add "needs code review" label
        if: (github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.draft == false) || (github.event_name == 'pull_request' && github.event.action == 'ready_for_review')
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["needs code review"]
            })
      - name: Remove "needs code review" label and add "QA Needed" label
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.pull_request.draft == false
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: "needs code review"
            });
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["QA Needed"]
            });
