name: Add "QA needed" label and remove "needs code review" label on approved pull request

on:
  pull_request_review:
    types: [submitted]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approved review
        if: github.event.review.state == 'approved'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: "needs code review"
            });
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["QA needed"]
            });
