name: Add "needs code review" label

on:
  pull_request:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add "needs code review" label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["needs code review"]
            })
