name: Add new preview link to related issue

on:
  pull_request:
    types: [opened]

jobs:
  add_link:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue number
        id: issue
        run: echo "::set-output name=number::$(jq --raw-output '.issue.number' $GITHUB_EVENT_PATH)"
      - name: Add environment link to issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            const previewLink = pullRequest.head.repo.html_url;
            const { data: comments } = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.issue.outputs.number }}
            });
            const existingComment = comments.find(comment => comment.user.login === 'github-actions[bot]' && comment.body.startsWith('Preview Link: '));
            if (!existingComment) {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ steps.issue.outputs.number }},
                body: `Preview Link: ${previewLink}`
              });
            } else if (!existingComment.body.endsWith(previewLink)) {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ steps.issue.outputs.number }},
                body: `Preview Link: ${previewLink}`
              });
            }
