name: Block Merge if QA Needed label is present

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened, ready_for_review]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Check for QA Needed label
      id: check_label
      run: |
        LABEL_NAME="QA needed"
        IS_PRESENT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels | jq '.[] | select(.name=="'"$LABEL_NAME"'")')
        if [[ -n "$IS_PRESENT" ]]; then
          echo "The label $LABEL_NAME is present, blocking merge"
          echo "::set-output name=merge::false"
        else
          echo "The label $LABEL_NAME is not present, merge can proceed"
          echo "::set-output name=merge::true"
        fi
    - name: Block merge if QA Needed
      run: |
        if [[ "${{ steps.check_label.outputs.merge }}" == "false" ]]; then
          echo "Blocking merge as the label 'QA needed' is present"
          exit 1
        fi
