name: Sync Labels between issues and the associated pull request

on:
  pull_request:
    types:
      - opened
      - synchronize
  issues:
    types:
      - labeled
      - unlabeled
      - edited

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Sync labels
        run: |
          # Retrieve necessary information
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          pr_labels=$(curl -sH "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$pr_number" | \
            jq --raw-output '.labels[].name')

          issue_number=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          issue_labels=$(curl -sH "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$issue_number" | \
            jq --raw-output '.labels[].name')

          # Compare labels and sync if necessary
          if [[ "$pr_labels" != "$issue_labels" ]]; then
            echo "Labels are not in sync. Updating issue labels..."
            curl -sX POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              -d "{\"labels\": $pr_labels}" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$issue_number/labels"
          else
            echo "Labels are already in sync."
          fi
